# A name for this workflow
name: Deploy to GitHub Pages

on:
  # This workflow will run every time you push code to your "main" branch
  push:
    branches: [ main ]
  
  # This allows you to run the workflow manually from the "Actions" tab on GitHub
  workflow_dispatch:

# These permissions are required for the workflow to work correctly
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # This is the "build" job, which prepares your site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use Node.js version 18

      - name: Install dependencies
        run: npm install

      - name: Build the Eleventy site
        run: npx @11ty/eleventy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # This is the "deploy" job, which publishes your site
  deploy:
    # This job depends on the "build" job completing successfully
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4